#!/sbin/sh

. "$env"
cd "$tmp"

if [ -f /system/system/vendor/lib/modules/pronto/pronto_wlan.ko ]; then
	print "Stock ROM detected"
	cat Image-custom | pigz -p 8 -nfc9 > Image.gz
else
	print "Custom ROM detected"
	cat Image-custom | pigz -p 8 -nfc9 > Image.gz
fi

exit 0
