#!/sbin/sh

. "$env"

cd "$ramdisk_patch" && [ "$(ls)" ] || exit 0

# fix permissions of patch files
chmod -R 0755 .

find -type f \( \
	-name "*.rc" ! -name "ueventd.*" \
	\) -exec chmod 0750 {} \;

find -type f \( \
	-name "*.xml" -o -name "*.do" -o -name "*.pem" -o -name "*.vtab" -o \
	-name "fstab.*" -o -name "*.prop" -o -name "*_contexts" -o \
	-name "ueventd.*" -o -name "sepolicy" -o -name "sepolicy_version" \
	\) -exec chmod 0644 {} \;

overlay="$ramdisk/overlay"

print "Copying new files..."
cp -rd ./. "$ramdisk/"
mkdir -p "$overlay"
cp -rd ./. "$overlay/"

import_rc "init.velocity.rc"
import_rc "init.spectrum.rc"

cp /system/init.rc "$overlay/"
insert_after_last "$overlay/init.rc" "import .*\.rc" "import /init.spectrum.rc"
insert_after_last "$overlay/init.rc" "import .*\.rc" "import /init.velocity.rc"

# silently fails if there's none
insert_after_last "$overlay/init.rc" "import .*\.rc" "import /init.magisk.rc"

if [ -f /system/system/vendor/lib/modules/pronto/pronto_wlan.ko ]; then
	cp -rd "$tmp/overlay/." "$overlay/"
fi

exit 0
