#!/sbin/sh

. "$env"
cd "$tmp"

print "Checking for Treble..."
if [ -e /dev/block/bootdevice/by-name/vendor_a ] && [ ! -L /system/vendor ]; then
    print "Treble ROM detected, enabling support..."
    cat treble.dtb >> Image.gz
else
    cat base.dtb >> Image.gz
fi

exit 0
